config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "groups#index"
  resources :users,only: [:edit, :update, :index]
  resources :groups,only: [:edit, :update, :new, :create] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.body? ? last_message.body : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :body, presence: true, unless: :image?
  mount_uploader :image, ImagesUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    @messages = Message.where('(group_id = ?) and (id > ?)', params[:group_id], params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end
  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end
  def edit
  end
  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end
  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html {redirect_to group_messages_path(@group), notice: 'メッセージが送信されました' } 
        format.json 
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end
  
  private
  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where('(name LIKE(?)) and (id != ?)', "%#{params[:keyword]}%", current_user.id)
    respond_to do |format|
      format.json 
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name,"グループ名", class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for:"chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input{name:"keyword", class: 'chat-group-form__input', placeholder: '追加したいユーザー名を入力してください',id:"serach-input"}
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for:"chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      .chat-group-users
        .chat-group-user.clearfix{id: "chat-group-user-#{current_user.id}"}
          %input{name:'group[user_ids][]',type:'hidden', value:"#{current_user.id}"}
          %p.chat-group-user__name 
            #{current_user.name}
        - group.users.each do |user|
          - if (user.id != current_user.id)
            .chat-group-user.clearfix{id: "chat-group-user-#{user.id}"}
              %input{name:'group[user_ids][]',type:'hidden', value:"#{user.id}"}
              %p.chat-group-user__name 
                #{user.name}
              .user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
                削除


  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
= render partial: "/side_menu"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield

app/views/messages/_message.html.haml
.messages__message{data:{id: "#{message.id}"}}
  .messages__message__info
    %p.messages__message__info__user-name
      =message.user.name
    %p.messages__message__info__date
      =message.created_at.strftime("%Y/%m/%d %H:%M")
  %p.messages__message__text
    - if message.body.present?
      = message.body
    - if message.image.present?
      = image_tag "#{message.image}"

app/views/messages/index.html.haml
= render partial: "/side_menu"

.chatspace
  .main-header
    .current-group{data:{group:{id: "#{@group.id}"}}}
      .current-group__name
        = @group.name
      %ul.current-group__meber-list
        Member:
        - @group.users.each do |user|
          %li
            = user.name
    .edit
      =link_to edit_group_path(@group), class: "edit__btn" do
        %p Edit
  .messages
    = render @messages
 
  .form
    = form_for [@group, @message],html: {class: 'form__box'} do |f|
      .form__box__input
        = f.text_field :body, class: 'form__box__input__text', placeholder: 'type a message'
        = f.label :image, class: 'form__box__input__img-label' do
          = fa_icon 'picture-o', class: 'icon'
          = f.file_field :image, class: 'form__box__input__img'
      = f.submit 'Send', class: 'form__box__submit'   

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'